<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPrsgx4n\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPrsgx4n/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPrsgx4n.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPrsgx4n\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPrsgx4n\appProdProjectContainer([
    'container.build_hash' => 'Prsgx4n',
    'container.build_id' => '3aa3713d',
    'container.build_time' => 1592197556,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPrsgx4n');
